export const siteConfig = {
	name: "Steven Suki",
	shortName: "StevSuki",
	role: "Native Developer",
	title: "Portofolio - Steven Suki",
	description: "Generated by create next app",
	socials: {
		instagram: "https://www.instagram.com/stevensuki_8/",
		linkedin: "https://www.linkedin.com/in/steven-suki-53a14b25a",
		github: "https://github.com/stevsuki",
		facebook: "https://www.facebook.com/steven.suki.5",
	},
};
